#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoggrData
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="Zoggr")]
	public partial class ZoggrDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertShow(Show instance);
    partial void UpdateShow(Show instance);
    partial void DeleteShow(Show instance);
    #endregion
		
		public ZoggrDataContext() : 
				base("Data Source=sql386.mysite4now.com;Initial Catalog=Zoggr;Persist Security Info=Tru" +
						"e;User ID=ZoggrWeb;Password=Zo88r", mappingSource)
		{
			OnCreated();
		}
		
		public ZoggrDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZoggrDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZoggrDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ZoggrDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Show> Shows
		{
			get
			{
				return this.GetTable<Show>();
			}
		}
	}
	
	[Table(Name="dbo.ZGR_Shows")]
	public partial class Show : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _ID;
		
		private string _ReplaySerialNumber;
		
		private string _TabId;
		
		private string _TabName;
		
		private string _ChannelId;
		
		private string _ChannelType;
		
		private string _ChannelTitle;
		
		private string _ShowTitle;
		
		private string _EpisodeId;
		
		private string _EpisodeTitle;
		
		private string _EpisodeDescription;
		
		private System.DateTime _EpisodeStartTimeGMT;
		
		private int _EpisodeDuration;
		
		private string _EpisodeQuality;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(long value);
    partial void OnIDChanged();
    partial void OnReplaySerialNumberChanging(string value);
    partial void OnReplaySerialNumberChanged();
    partial void OnTabIdChanging(string value);
    partial void OnTabIdChanged();
    partial void OnTabNameChanging(string value);
    partial void OnTabNameChanged();
    partial void OnChannelIdChanging(string value);
    partial void OnChannelIdChanged();
    partial void OnChannelTypeChanging(string value);
    partial void OnChannelTypeChanged();
    partial void OnChannelTitleChanging(string value);
    partial void OnChannelTitleChanged();
    partial void OnShowTitleChanging(string value);
    partial void OnShowTitleChanged();
    partial void OnEpisodeIdChanging(string value);
    partial void OnEpisodeIdChanged();
    partial void OnEpisodeTitleChanging(string value);
    partial void OnEpisodeTitleChanged();
    partial void OnEpisodeDescriptionChanging(string value);
    partial void OnEpisodeDescriptionChanged();
    partial void OnEpisodeStartTimeGMTChanging(System.DateTime value);
    partial void OnEpisodeStartTimeGMTChanged();
    partial void OnEpisodeDurationChanging(int value);
    partial void OnEpisodeDurationChanged();
    partial void OnEpisodeQualityChanging(string value);
    partial void OnEpisodeQualityChanged();
    #endregion
		
		public Show()
		{
			OnCreated();
		}
		
		[Column(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[Column(Storage="_ReplaySerialNumber", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ReplaySerialNumber
		{
			get
			{
				return this._ReplaySerialNumber;
			}
			set
			{
				if ((this._ReplaySerialNumber != value))
				{
					this.OnReplaySerialNumberChanging(value);
					this.SendPropertyChanging();
					this._ReplaySerialNumber = value;
					this.SendPropertyChanged("ReplaySerialNumber");
					this.OnReplaySerialNumberChanged();
				}
			}
		}
		
		[Column(Storage="_TabId", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string TabId
		{
			get
			{
				return this._TabId;
			}
			set
			{
				if ((this._TabId != value))
				{
					this.OnTabIdChanging(value);
					this.SendPropertyChanging();
					this._TabId = value;
					this.SendPropertyChanged("TabId");
					this.OnTabIdChanged();
				}
			}
		}
		
		[Column(Storage="_TabName", DbType="VarChar(75) NOT NULL", CanBeNull=false)]
		public string TabName
		{
			get
			{
				return this._TabName;
			}
			set
			{
				if ((this._TabName != value))
				{
					this.OnTabNameChanging(value);
					this.SendPropertyChanging();
					this._TabName = value;
					this.SendPropertyChanged("TabName");
					this.OnTabNameChanged();
				}
			}
		}
		
		[Column(Storage="_ChannelId", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string ChannelId
		{
			get
			{
				return this._ChannelId;
			}
			set
			{
				if ((this._ChannelId != value))
				{
					this.OnChannelIdChanging(value);
					this.SendPropertyChanging();
					this._ChannelId = value;
					this.SendPropertyChanged("ChannelId");
					this.OnChannelIdChanged();
				}
			}
		}
		
		[Column(Storage="_ChannelType", DbType="VarChar(25) NOT NULL", CanBeNull=false)]
		public string ChannelType
		{
			get
			{
				return this._ChannelType;
			}
			set
			{
				if ((this._ChannelType != value))
				{
					this.OnChannelTypeChanging(value);
					this.SendPropertyChanging();
					this._ChannelType = value;
					this.SendPropertyChanged("ChannelType");
					this.OnChannelTypeChanged();
				}
			}
		}
		
		[Column(Storage="_ChannelTitle", DbType="VarChar(125) NOT NULL", CanBeNull=false)]
		public string ChannelTitle
		{
			get
			{
				return this._ChannelTitle;
			}
			set
			{
				if ((this._ChannelTitle != value))
				{
					this.OnChannelTitleChanging(value);
					this.SendPropertyChanging();
					this._ChannelTitle = value;
					this.SendPropertyChanged("ChannelTitle");
					this.OnChannelTitleChanged();
				}
			}
		}
		
		[Column(Storage="_ShowTitle", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string ShowTitle
		{
			get
			{
				return this._ShowTitle;
			}
			set
			{
				if ((this._ShowTitle != value))
				{
					this.OnShowTitleChanging(value);
					this.SendPropertyChanging();
					this._ShowTitle = value;
					this.SendPropertyChanged("ShowTitle");
					this.OnShowTitleChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeId", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EpisodeId
		{
			get
			{
				return this._EpisodeId;
			}
			set
			{
				if ((this._EpisodeId != value))
				{
					this.OnEpisodeIdChanging(value);
					this.SendPropertyChanging();
					this._EpisodeId = value;
					this.SendPropertyChanged("EpisodeId");
					this.OnEpisodeIdChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeTitle", DbType="VarChar(125) NOT NULL", CanBeNull=false)]
		public string EpisodeTitle
		{
			get
			{
				return this._EpisodeTitle;
			}
			set
			{
				if ((this._EpisodeTitle != value))
				{
					this.OnEpisodeTitleChanging(value);
					this.SendPropertyChanging();
					this._EpisodeTitle = value;
					this.SendPropertyChanged("EpisodeTitle");
					this.OnEpisodeTitleChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeDescription", DbType="VarChar(500) NOT NULL", CanBeNull=false)]
		public string EpisodeDescription
		{
			get
			{
				return this._EpisodeDescription;
			}
			set
			{
				if ((this._EpisodeDescription != value))
				{
					this.OnEpisodeDescriptionChanging(value);
					this.SendPropertyChanging();
					this._EpisodeDescription = value;
					this.SendPropertyChanged("EpisodeDescription");
					this.OnEpisodeDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeStartTimeGMT", DbType="DateTime NOT NULL")]
		public System.DateTime EpisodeStartTimeGMT
		{
			get
			{
				return this._EpisodeStartTimeGMT;
			}
			set
			{
				if ((this._EpisodeStartTimeGMT != value))
				{
					this.OnEpisodeStartTimeGMTChanging(value);
					this.SendPropertyChanging();
					this._EpisodeStartTimeGMT = value;
					this.SendPropertyChanged("EpisodeStartTimeGMT");
					this.OnEpisodeStartTimeGMTChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeDuration", DbType="Int NOT NULL")]
		public int EpisodeDuration
		{
			get
			{
				return this._EpisodeDuration;
			}
			set
			{
				if ((this._EpisodeDuration != value))
				{
					this.OnEpisodeDurationChanging(value);
					this.SendPropertyChanging();
					this._EpisodeDuration = value;
					this.SendPropertyChanged("EpisodeDuration");
					this.OnEpisodeDurationChanged();
				}
			}
		}
		
		[Column(Storage="_EpisodeQuality", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string EpisodeQuality
		{
			get
			{
				return this._EpisodeQuality;
			}
			set
			{
				if ((this._EpisodeQuality != value))
				{
					this.OnEpisodeQualityChanging(value);
					this.SendPropertyChanging();
					this._EpisodeQuality = value;
					this.SendPropertyChanged("EpisodeQuality");
					this.OnEpisodeQualityChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
