<?xml version="1.0" encoding="utf-8"?>
<Database Name="Zoggr" Class="ZoggrDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="ConnectionString" ConnectionString="Data Source=sql386.mysite4now.com;Initial Catalog=Zoggr;Persist Security Info=True;User ID=ZoggrWeb;Password=Zo88r" Provider="System.Data.SqlClient" />
  <Table Name="dbo.ZGR_Shows" Member="Shows">
    <Type Name="Show">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ReplaySerialNumber" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="TabId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="TabName" Type="System.String" DbType="VarChar(75) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelType" Type="System.String" DbType="VarChar(25) NOT NULL" CanBeNull="false" />
      <Column Name="ChannelTitle" Type="System.String" DbType="VarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="ShowTitle" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeId" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeTitle" Type="System.String" DbType="VarChar(125) NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeDescription" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeStartTimeGMT" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeDuration" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="EpisodeQuality" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>